name: hanoi_tower_control
description: Component to be used to control Hanoi Tower games.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  collection: ^1.14.12
  stack: ^0.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
